name: OutRunManila
favicon: null
layout_spectrum: 0.9616425237618387
typography_spectrum: 0.4017682448029518
title: Run with Pride!
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#732a85'
    - '#0c8040'
    - '#f9ee13'
    - '#f68c1f'
    - '#00ff00'
  brandStrength: 0.06797642400488257
  lightness: 0.4770559996832162
  saturation: 0.2442891134414822
  rhythmicContrast: 0.4627539971843362
purpose: []
